name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      - run: make setup
      # Adds formatter annotations to the commit. This is in charge of reporting
      # fromatting errors but not halting the CI job on failure — we use
      # `--error-on-warnings=false` here and a single full pass with `make
      # lint-ci` below.
      - run: make lint-ci-formatter-annotations
      - run: make lint-ci
