name: Pull request linter review

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      - uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
        with:
          reviewdog_version: latest
      - run: make setup
      - name: Run lint through `reviewdog` for pull request comments
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make lint-ci-comments-rdjson | reviewdog -f=rdjson -reporter=github-pr-review
